[package]
name = "mini_miner"
version = "0.1.0"
authors = ["Alex Kofke <akofke@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7.1"
rand = "0.5.0"
byteorder = "1.2.3"
