[package]
name = "help_me_unpack"
version = "0.1.0"
authors = ["Alex Kofke <akofke@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "0.9.1"
byteorder = "1.2.3"

